### ISSUE TITLE
Stdout calls are not always captured

### ISSUE THREAD

**Issue by pavelsaman** [christiansandberg/pytest-reporter-html1#1]
I have the following problem. At least I think it's not anything wrong with my test case.

A simplified version where I still encounter problems is:

```python
@pytest.mark.only
@pytest.mark.db
@pytest.mark.parametrize("attribute, attr_value", CSVReader.read_from_csv("Resources/Cards/filter_cards.csv"))
def test_get_cards_by_one_param(self, attribute, attr_value):
    response = requests.get(f"{Config.base_url()}/{API_ENDPOINT}",
                            headers={"Authorization": f'Basic {Config.API_KEY["Store"]}'},
                            params={attribute: attr_value})

    assert response.status_code == 200
    assert response.reason == "OK"

    print(response.text)
```

When I open the report generated by **pytest-html v2.1.1**, I can see:

![image](https://user-images.githubusercontent.com/24702416/84000707-73559100-a965-11ea-9e44-a33b809c1b67.png)

For each parametrization, there's a captured stdout call as expected.

When I open the report generated by **reporter-html1: 0.3.4**, then I see:

![image](https://user-images.githubusercontent.com/24702416/84000813-b1eb4b80-a965-11ea-9564-1a7071949587.png)

**Where is the second stdout message?** I think it's missing from some reason.

This doesn't happen every time, sometimes all calls are captured, sometimes some of them are missing, I don't see any pattern in it.

I'm using python 3.7.4 and reporter-html1 0.3.4.

If more information is needed, let me know, I'll try to look into it a bit more.

**Comment by christiansandberg** [comment]
It could be related to how we try to avoid printing the same captures multiple times. Since captured output is associated to an item instead of a call, and a single item can be rerun multiple times, we need to remember which captures have been previously printed. This is probably not handled correctly and therefore a capture with identical content as one before will not be printed.

**Comment by pavelsaman** [comment]
> 
> 
> It could be related to how we try to avoid printing the same captures multiple times. Since captured output is associated to an item instead of a call, and a single item can be rerun multiple times, we need to remember which captures have been previously printed. This is probably not handled correctly and therefore a capture with identical content as one before will not be printed.

I can confirm that on my set of requests. One of the previous calls in my case also prints out `{"Cards":[],"CardTotalCount":0}`, and the first such printout is actually visible in the report.
