### ISSUE TITLE
Encoding problem with degree character

### ISSUE THREAD

**Issue by PierreLeger8** [christiansandberg/pytest-reporter-html1#11]
If a print in pytest something like:
`print('Temperature 30°C')`
I get following output in the html report:
`Temperature 30?C`
I played around in the template with the following line but nothing helps:
`<pre><samp>{{ content|escape|replace('\r\n', '\n')|ansi|safe }}</samp></pre>`
Any suggestions?

**Comment by christiansandberg** [comment]
I've fixed it in [pytest-reporter v0.5.2](https://github.com/christiansandberg/pytest-reporter/releases/tag/v0.5.2). Please update and see if it works.

```
pip install -U pytest-reporter
```

**Comment by PierreLeger8** [comment]
Perfect, it works. Thanks
