### ISSUE TITLE
gihub actions CI/CD error unrecognized arguments: --template=html1/index.html

### ISSUE THREAD

**Issue by kunaal-ai** [christiansandberg/pytest-reporter-html1#18]
Using playwright (Version 1.35.0), Python 3.10.9, and pytest 7.1.2

Running test locally, generating reports successfully ✅

But as soon I pushed code, getting ❌ failed build with error on arguments:

![Screenshot 2023-09-17 at 4 01 05 AM](https://github.com/christiansandberg/pytest-reporter-html1/assets/46636573/0f05e4ff-b14c-4aa3-b266-f636087ca1ff)

### pytest.ini
```
[pytest]

python_files = test_*
addopts = -ra -s 
    --base-url=https://para.testar.org/parabank/index.htm/
    #--browser chromium --browser firefox --browser webkit 
    --template=html1/index.html 
    --report=results/report.html
    --screenshot only-on-failure

markers =
    smoke: marks tests as slow (deselect with '-m "not smoke"')
```

### yml file
[yml file](https://github.com/kunaal-ai/paraBank/pull/12/commits/d9a03c5a793ad6e58d586d0de2376a9af8c1b090)

Anu suggestions please, how this issue can be resolved？ 
Thanks !!

**Comment by christiansandberg** [comment]
You probably need to update your GitHub workflow to include pytest-reporter-html1 in a pip install command.

**Comment by kunaal-ai** [comment]
> You probably need to update your GitHub workflow to include pytest-reporter-html1 in a pip install command.

Thank you so much, I was trying ```python -m pip install pytest-reporter-html1``` which did not work. But eventually ```pip install pytest-reporter-html1``` worked fine and build is green.
