### ISSUE TITLE
Extras does not work.

### ISSUE THREAD

**Issue by Stefanhg** [christiansandberg/pytest-reporter-html1#19]
Hello,
I have been playing around with this and I can't get the extras part to work. On top of that the testcases for testing extras are not sufficient at all as it does not test anything. 

I used this as test example:
```
from pytest_html import extras as extra2

def test_extra(extras):
    print("This is a message")
    extras.append(extra2.text("some string"))
```

**Comment by Stefanhg** [comment]
A misunderstanding from my side.
I since it was also called "extras" it also used the pytest_html one but it does not. You have to add it manually.

**Comment by christiansandberg** [comment]
This is a feature in pytest-reporter-html1 which would support extras from pytest-html, but I think I misspelled it as extra instead of extras.

But yes, one problem is that to get access to the extras fixture you need to install pytest-html as well unless you add it to the report manually.

**Comment by Stefanhg** [comment]
Yeah it should be possible to use pytest-html to do this. But I think it would be better to implement the feature as a part of the package instead.
I moved the extra function request to pytest-reporter instead as I think it would be better to implement the feature there.
