### ISSUE TITLE
Malformed HTML

### ISSUE THREAD

**Issue by doerwalter** [christiansandberg/pytest-reporter-html1#2]
The generated HTML report works in all browsers, however the HTML seems to be malformed. The code contains a duplicate `</style>` end tag, i.e. 

```html
<title>Test Report</title><style>
        ... lots of CSS ...
  </style></style>
```

Furthermore the HTML validator at https://validator.w3.org/ complains about:

    Element div not allowed as child of element summary in this context.

in contexts like this:

```
<summary> <div class="title test-title"> <div ...
```

**Comment by christiansandberg** [comment]
Thanks for pointing that out! I think I fixed it, I just hope I haven't broken anything else so I'll check the report in some other browsers than Chrome tomorrow.
