### ISSUE TITLE
Put warnings in a jinja block

### ISSUE THREAD

**Issue by Remi-Gau** [christiansandberg/pytest-reporter-html1#23]
Tempted to use this template for a project that I maintain.

We a LOT of warnings when running our test suite so I'd like to be able to collapse the warning section in a details HTML element.

Unless I am mistaken at the moment I have to pretty much use the whole template and tweak it because I cannot just inherit and tweak the warning section because it is not in a jinja block.

Do you think it would be OK to add a block for the warning section to make the template more modular?

**Comment by Remi-Gau** [comment]
I can open a PR if you think this is worth doing.

**Comment by christiansandberg** [comment]
Good idea. Please make a PR! I also think making it collapsed by default is better than how it is now.
