### ISSUE TITLE
doc test not renderered properly

### ISSUE THREAD

**Issue by Remi-Gau** [christiansandberg/pytest-reporter-html1#27]
doc tests will all contain the following

```
An undefined that is chainable, where both __getattr__ and __getitem__ return itself rather than raising an [:exc:`UndefinedError`](file:///home/remi/github/pytest-reporter-html1/report.html#system-message-1).

System Message: ERROR/3 (<string>, line 1); [backlink](file:///home/remi/github/pytest-reporter-html1/report.html#problematic-1)

Unknown interpreted text role "exc".

>>> foo = ChainableUndefined(name='foo')
>>> str(foo.bar['baz'])
''
>>> foo.bar['baz'] + 42
Traceback (most recent call last):
  ...
jinja2.exceptions.UndefinedError: 'foo' is undefined

System Message: ERROR/3 (<string>, line 13)

Unknown directive type "versionadded".

.. versionadded:: 2.11.0
```

## Steps to reproduce

create a `module_with_doctest.py`

```python
def function_with_test_in_docstring():
    """
    >>> a = ["a", "b"]
    >>> "_".join(a)
    'a_b'
    """
    ...


def test_dummy():
    function_with_test_in_docstring()
```

run pytest on it with `--doctest-modules`

```bash
pytest --doctest-modules module_with_doctest.py --report=report.html -vv --template pytest_reporter_html1/templates/html1/index.html
```

Report content

![image](https://github.com/user-attachments/assets/11bffedd-3575-47ab-be47-5256e8d33599)

**Comment by Remi-Gau** [comment]
Maybe having doc tests rendered after the "normal" tests could also be a nice thing for the navigability of the report.

**Comment by christiansandberg** [comment]
Thanks for the report. I haven't used doctest, but I could reproduce it in the branch bugfix/27-doctest-support. No idea what is going on though...

**Comment by christiansandberg** [comment]
Fixed the incorrect documentation. Can't see a way currently to get the doctest represented inside the report somehow though.

![image](https://github.com/user-attachments/assets/c5c90b56-8512-4f99-a32f-b6ed3420ba69)

**Comment by Remi-Gau** [comment]
thanks for the quick fix!
