### ISSUE TITLE
installing htmlmin fails with python 3.13 

### ISSUE THREAD

**Issue by Remi-Gau** [christiansandberg/pytest-reporter-html1#31]
see this issue: https://github.com/mankyd/htmlmin/issues/66

**Comment by Remi-Gau** [comment]
fix for now would be to switch to htmlmin2 (released from non-officially maintained fork that at least fixes the 3.13 issue)

**Comment by christiansandberg** [comment]
If you want to make PR I can merge it. 👍

**Comment by Remi-Gau** [comment]
Will do but beware that this may also just be a temporary solution: see https://github.com/mankyd/htmlmin/issues/49#issuecomment-1471458662 and the follow up discussion

**Comment by Remi-Gau** [comment]
Updated in https://github.com/christiansandberg/pytest-reporter-html1/pull/32

**Comment by christiansandberg** [comment]
Perhaps it's not the most important feature of this library. Could also consider skipping minification.

**Comment by Remi-Gau** [comment]
yeah the idea crossed my mind too

**Comment by Remi-Gau** [comment]
selfish request: I will need a new release to able to use it on python 3.13 with package I maintain. 🙏🏾 🙈

**Comment by Remi-Gau** [comment]
Merci !!!!
