### ISSUE TITLE
Template crashing with excinfo object empty

### ISSUE THREAD

**Issue by fwilmsh** [christiansandberg/pytest-reporter-html1#4]
This more like a question:
I have a complex setup and am trying to use your sample html template for reporting. 
It did work really well so far. But now I came across an issue where the rendering of the report will fail on the following line:
`<pre>{{ phase.call.excinfo.exconly(tryshort=True) }}</pre>`. 
`jinja2.exceptions.UndefinedError: 'None' has no attribute 'exconly'`
So this usually means that `excinfo` is just not there in this case. 
The test run was parametrized with float numbers and did fail on one instantiation. When all parameter sets succeed the report is also fine as it seems at the moment.
I only had a quick look over the source here, but could not really find excinfo in your python code when building the context, so I'm guessing that may be some part of the pytest data structures. 
I'm not 100% of all assumptions above, just need some help to pinpoint this a bit further. 
Let me know what else is needed to pinpoint this better or what more info I can provide. Thanks!

**Comment by christiansandberg** [comment]
Not sure why that would happen but I've published a new version that should hopefully fix that.

**Comment by fwilmsh** [comment]
Thanks for the quick fix @christiansandberg. Really appreciate it. 
I wasn't able to crash it anymore with the new version. Even more glad I don't have to debug into that myself ;)
Thanks again!
